### ISSUE TITLE
Icons not updated in app drawer but changed if browsed through Settings - Lock Screen - Add shortcuts

### ISSUE THREAD

**Issue by raketti** [fravaccaro/harbour-themepack-xenlism-wildfire#1]
I noticed two icons that were not updated in the app view, but do have an app icon. They are changed if the apps are browsed through Settings -> Lock Screen -> Add Shortcuts (freely translated).

**Voyager**
App drawer: https://imgur.com/l8KIltQ
Through settings: https://imgur.com/rvQVsHz

**Situations**
App drawer: https://imgur.com/lqO1WXN
Settings: https://imgur.com/z0RZS2j

**Comment by fravaccaro** [comment]
Did you restart the homescreen?

**Comment by raketti** [comment]
Yes. Also tried reverting to the original icons and readding the icon pack.

**Comment by fravaccaro** [comment]
Which device do you have?

**Comment by raketti** [comment]
Sorry, should have mentioned the details:
SFOS 3.0.1.11
Xperia XA2

**Comment by raketti** [comment]
Thanks! Working great!
https://i.imgur.com/HYLpII9.png
https://i.imgur.com/ntAk8gT.png

**Comment by fravaccaro** [comment]
ole hyvä :)
